source/BlueDataWeb/Models/Entites/ImagePage.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDataWeb.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagePage
    {
        public int ID { get; set; }
        public string KeyName { get; set; }
        public string Image { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
    }
}

source/BlueDataWeb/Areas/Admin/Controllers/ImagePageController.cs
using BlueDataWeb.Areas.Admin.Models.Service;
using BlueDataWeb.Models.Entites;
using BlueDataWeb.Utility;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlueDataWeb.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin, AdminCategory")]
    public class ImagePageController : Controller
    {
        private ImageService imgservice = new ImageService();

        private BlueDataWebEntities db = new BlueDataWebEntities();

  

        //
        // GET: /Admin/Category/

        public ActionResult Index()
        {
            var images = db.ImagePages;
            return View(images.ToList());
        }

        //
        // GET: /Admin/Category/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Admin/Category/Create

        [HttpPost]
        public ActionResult Create(ImagePage imagePage)
        {
            if (ModelState.IsValid)
            {
                

                #region xử lý upload image

                if (Request.Files["img"] != null)
                {
                    string fullname = Request.Files["img"].FileName;
                    if (fullname != "")
                    {
                        imagePage.Image = UploadImageHelper.Upload(Request.Files["img"], Server.MapPath("~/Images/"), "News");
                    }
                }

                #endregion xử lý upload image



                db.ImagePages.Add(imagePage);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(imagePage);
        }

        //
        // GET: /Admin/Category/Edit/5

        public ActionResult Edit(int id = 0)
        {
            ImagePage imagePage = db.ImagePages.Find(id);

            return View(imagePage);
        }

        //
        // POST: /Admin/Category/Edit/5

        [HttpPost]
        public ActionResult Edit(ImagePage imagePage)
        {
            if (ModelState.IsValid)
            {
                #region xử lý upload image

                if (Request.Files["img"] != null)
                {
                    string fullname = Request.Files["img"].FileName;
                    if (fullname != "")
                    {
                        imagePage.Image = UploadImageHelper.Upload(Request.Files["img"], Server.MapPath("~/Images/"), "News");
                    }
                }

                #endregion xử lý upload image


                db.Entry(imagePage).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(imagePage);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

source/BlueDataWeb/Controllers/ImagePageController.cs
using BlueDataWeb.Models.Entites;
using BlueDataWeb.Paging;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;

namespace BlueDataWeb.Controllers
{
    public class ImagePageController : Controller
    {
        private BlueDataWebEntities db = new BlueDataWebEntities();



        public ActionResult GetByKeyName(string keyName)
        {

            ImagePage data = db.ImagePages.Where(x => x.KeyName.ToUpper() == keyName.ToUpper()).FirstOrDefault();
            TempData["Description"] = data.MetaDescription;
            TempData["Keywords"] = data.MetaKeywords;
            return PartialView("_BannerPage", data);
        }


        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

source/BlueDataWeb/Areas/Admin/Views/ImagePage/Create.cshtml
@model BlueDataWeb.Models.ImagePage

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create", "ImagePage", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <div class="mar10 borall">
        <div class="floatl">
            <span class="floatl">
                <img src="/Areas/Admin/images/icon-48-generic.png" />
            </span>
            <span class="title-name">Thêm ImagePage</span>
        </div>
        <ul class="floatr toolbar-list">
            <li id="toolbar-cancel" class="button">
                <a class="toolbar" href="/admin/ImagePage/Index">
                    <span class="icon-32-cancel"></span>
                    Hủy bỏ
                </a>
            </li>
            <li class="button">
                <div class="toolbar">
                    <span class="icon-32-apply"></span>
                    <input type="submit" value="Lưu" />
                </div>
            </li>
        </ul>
    </div>
    <!--end borall-->
    <div class="clear0"></div>
    <div class="mar10 borall">
        <div class="div100">
            <fieldset class="fromlist">
                <legend>Create</legend>
                <ul>
                    <li>
                        @Html.LabelFor(model => model.KeyName, "KeyName")
                        @Html.TextBoxFor(model => model.KeyName, new { size = "70" })
                    </li>
                    <li>
                        @Html.LabelFor(model => model.MetaKeywords, "MetaKeywords")
                        @Html.TextBoxFor(model => model.MetaKeywords, new { size = "70" })
                    </li>

                    <li>
                        @Html.LabelFor(model => model.MetaDescription, "MetaDescription")
                        @Html.TextBoxFor(model => model.MetaDescription, new { size = "70" })
                    </li>

                    <li>
                        @Html.LabelFor(model => model.Image, "Hình(1366*380)")
                        <input type="file" name="img" id="img" />
                        @Html.ValidationMessageFor(model => model.Image, null, new { @class = "validate" })
                    </li>
                </ul>
            </fieldset>
        </div>
    </div>
}

source/BlueDataWeb/Areas/Admin/Views/ImagePage/Edit.cshtml
@model BlueDataWeb.Models.ImagePage

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm("Edit", "ImagePage", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <div class="mar10 borall">
        <div class="floatl">
            <span class="floatl">
                <img src="/Areas/Admin/images/icon-48-generic.png" />
            </span>
            <span class="title-name">Chỉnh sửa ImagePage</span>
        </div>
        <ul class="floatr toolbar-list">
            <li id="toolbar-cancel" class="button">
                <a class="toolbar" href="/admin/ImagePage/Index">
                    <span class="icon-32-cancel"></span>
                    Hủy bỏ
                </a>
            </li>
            <li class="button">
                <div class="toolbar">
                    <span class="icon-32-apply"></span>
                    <input type="submit" value="Lưu" />
                </div>
            </li>
        </ul>
    </div>
    <!--end borall-->
    <div class="clear0"></div>
    <div class="mar10 borall">
        <div class="div100">
            <fieldset class="fromlist">
                <legend>Edit</legend>
                <ul>
                    <li>
                        @Html.HiddenFor(model => model.ID)

                        @Html.HiddenFor(model => model.KeyName)
                    </li>
                    <li>
                        @Html.LabelFor(model => model.KeyName, "KeyName")
                        @Html.TextBoxFor(model => model.KeyName, new { size = "70", @readonly = true })
                    </li>
                    <li>
                        @Html.LabelFor(model => model.MetaKeywords, "MetaKeywords")
                        @Html.TextBoxFor(model => model.MetaKeywords, new { size = "70" })
                    </li>

                    <li>
                        @Html.LabelFor(model => model.MetaDescription, "MetaDescription")
                        @Html.TextBoxFor(model => model.MetaDescription, new { size = "70" })
                    </li>

                    <li>
                        @Html.LabelFor(model => model.Image, "Hình(1366*380)")

                        <input type="file" name="img" />
                        <div>@Html.EditorFor(model => model.Image)</div>
                        <img src="/Images/ImagePage/@(Model.Image)" />
                        @Html.ValidationMessageFor(model => model.Image, null, new { @class = "validate" })
                    </li>
                </ul>
            </fieldset>
        </div>
    </div>
}

source/BlueDataWeb/Areas/Admin/Views/ImagePage/Index.cshtml
@model IEnumerable<BlueDataWeb.Models.Entites.ImagePage>

@{
    ViewBag.Title = "Index";
}

<div class="mar10 borall">
    <div class="floatl">
        <span class="floatl">
            <img src="/Areas/Admin/images/icon-48-generic.png" />
        </span>
        <span class="title-name">ImagePage</span>
    </div>
    <ul class="floatr toolbar-list">
        <li class="button">
            <a class="toolbar" href="/admin/ImagePage/Create">
                <span class="icon-32-new"></span>
                Thêm mới
            </a>
        </li>
    </ul>
</div>
<!--end borall-->

<div class="clear0"></div>
<div class="mar10 borall">
    <table class="formtable">
        <tr>
            <th>
                Hình
            </th>
            <th>
                KeyName
            </th>
            <th>
                MetaKeywords
            </th>
            <th>
                MetaDescription
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img src="/Images/ImagePage/@item.Image" width="140px" height="70px" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KeyName)
                </td>
                <td style="width:600px">

                    @Html.Raw(item.MetaKeywords)
                </td>

                <td style="width:600px">

                    @Html.Raw(item.MetaDescription)
                </td>
                <td>
                    <a class="button blue" title="Sửa" href="/admin/ImagePage/Edit/@item.ID">
                        <div class="icon">
                            <p class="ic-edit"></p>
                        </div>
                    </a>
                    
                </td>
            </tr>
        }

    </table>
</div>