source/BlueDataWeb/Models/Entites/Membership.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDataWeb.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership
    {
        public Membership()
        {
            this.UsersInRoles = new HashSet<UsersInRole>();
        }
    
        public int UserId { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public string Password { get; set; }
        public Nullable<int> PasswordFormat { get; set; }
        public string PasswordSalt { get; set; }
        public string Email { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsLockedOut { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastPasswordChangedDate { get; set; }
        public Nullable<System.DateTime> LastLockoutDate { get; set; }
        public Nullable<int> FailedPasswordAttemptCount { get; set; }
        public Nullable<System.DateTime> FailedPasswordAttemptWindowStart { get; set; }
        public Nullable<int> FailedPasswordAnswerAttemptCount { get; set; }
        public Nullable<System.DateTime> FailedPasswordAnswerAttemptWindowsStart { get; set; }
        public string Comment { get; set; }
        public string Username { get; set; }
    
        public virtual ICollection<UsersInRole> UsersInRoles { get; set; }
    }
}

source/BlueDataWeb/Models/Entites/Profile.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDataWeb.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public System.Guid UserId { get; set; }
        public string PropertyNames { get; set; }
        public string PropertyValueStrings { get; set; }
        public byte[] PropertyValueBinary { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    }
}

source/BlueDataWeb/Areas/Admin/Controllers/MembershipController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlueDataWeb.Models.Entites;


namespace BlueDataWeb.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin, AdminMember")]
    public class MembershipController : Controller
    {
        private BlueDataWebEntities db = new BlueDataWebEntities();

        //
        // GET: /Admin/Membership/

        public ActionResult Index()
        {
            ViewBag.lstrole = db.UsersInRoles.ToList();
            return View(db.Memberships.ToList());
        }

        //
        // GET: /Admin/Membership/Details/5

        public ActionResult Details(int id = 0)
        {
            var lstuserrole = db.UsersInRoles.ToList();
            ViewBag.lstuserrole = lstuserrole;
            Membership membership = db.Memberships.Find(id);
            ViewBag.userid = membership.UserId;

            if (membership == null)
            {
                return HttpNotFound();
            }
            return View(membership);
        }

        //
        //mã hóa md5 pass
        public static byte[] encryptData(string data)
        {
            System.Security.Cryptography.MD5CryptoServiceProvider md5Hasher = new System.Security.Cryptography.MD5CryptoServiceProvider();
            byte[] hashedBytes;
            System.Text.UTF8Encoding encoder = new System.Text.UTF8Encoding();
            hashedBytes = md5Hasher.ComputeHash(encoder.GetBytes(data));
            return hashedBytes;
        }
        public static string md5(string data)
        {
            return BitConverter.ToString(encryptData(data)).Replace("-", "").ToLower();

            //
            // GET: /User/Edit/5
        }
        // GET: /Admin/Membership/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Admin/Membership/Create

        [HttpPost]
        public ActionResult Create(Membership membership, UsersInRole role)
        {
            var usernametest = db.Memberships.Where(m => m.Username == membership.Username).FirstOrDefault();
            var emailtest = db.Memberships.Where(m => m.Email == membership.Email).FirstOrDefault();
            if (usernametest != null)
            {
                ViewBag.usernametest = "Tên đăng nhập đã tồn tại";
                return View();
            }
            if (emailtest != null)
            {
                ViewBag.emailtest = "Email đã tồn tại";
                return View();
            }

            if (ModelState.IsValid)
            {
                User usertest = db.Users.Where(m => m.Email == membership.Email).FirstOrDefault();
                if (usertest != null)
                {
                    usertest.Password = membership.Password;
                    db.Entry(usertest).State = EntityState.Modified;
                }
                else
                {
                    User user = new User()
                    {
                        Email = membership.Email,
                        Password = membership.Password,
                        Name = membership.Username
                    };

                    db.Users.Add(user);
                }

                membership.Password = md5(membership.Password);
                db.Memberships.Add(membership);
                db.SaveChanges();
                var roles = db.Roles.ToList();
                role.UserId = membership.UserId;
                foreach (var ro in roles)
                {
                    var chk = Request.Form["chk" + ro.RoleId];
                    if (chk == "on")
                    {
                        role.RoleId = ro.RoleId;

                        if (ModelState.IsValid)
                        {
                            db.UsersInRoles.Add(role);
                            db.SaveChanges();

                        }

                    }
                }
                return RedirectToAction("Index");
            }

            return View(membership);
        }

        //
        // GET: /Admin/Membership/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Membership membership = db.Memberships.Find(id);
            ViewBag.userid2 = membership.UserId;
            var lstrole = db.UsersInRoles.Where(m => m.UserId == membership.UserId).ToList();
            ViewBag.lstrole = lstrole;
            if (membership == null)
            {
                return HttpNotFound();
            }
            return View(membership);
        }

        //
        // POST: /Admin/Membership/Edit/5

        [HttpPost]
        public ActionResult Edit(Membership membership, UsersInRole role)
        {
            int i = membership.UserId;
            //rm
            //BlueDataWebEntities dbnew2 = new BlueDataWebEntities();
            var uirole = db.UsersInRoles.Where(d => d.UserId == i).ToList();
            foreach (var u in uirole)
            {
                db.UsersInRoles.Remove(u);
                db.SaveChanges();
            }
            BlueDataWebEntities dbnew = new BlueDataWebEntities();

            string s = membership.Password;
            Membership membertest = dbnew.Memberships.Where(m => m.Username == membership.Username).FirstOrDefault();
            if (membership.Password != null || membership.Password == "")
            {
                membership.Password = md5(membership.Password);
            }
            if (membership.Password == null || membership.Password == "")
            {
                membership.Password = membertest.Password;
            }
            membership.LastLoginDate = membertest.LastLoginDate;
            if (ModelState.IsValid)
            {
                User usertest = db.Users.Where(m => m.Email == membership.Email).FirstOrDefault();
                if (usertest != null)
                {
                    usertest.Password = membership.Password;
                    db.Entry(usertest).State = EntityState.Modified;
                }
                else
                {
                    User user = new User()
                    {
                        Email = membership.Email,
                        Password = membership.Password,
                        Name = membership.Username
                        
                    };

                    db.Users.Add(user);
                }

                db.Entry(membership).State = EntityState.Modified;
                db.SaveChanges();
                var roles = db.Roles.ToList();
                role.UserId = membership.UserId;
                foreach (var ro in roles)
                {
                    var chk = Request.Form["check" + ro.RoleId];
                    if (chk == "on")
                    {
                        role.RoleId = ro.RoleId;

                        if (ModelState.IsValid)
                        {
                            db.UsersInRoles.Add(role);
                            db.SaveChanges();

                        }

                    }
                }
                return RedirectToAction("Index");
            }
            return View(membership);
        }

        //
        // GET: /Admin/Membership/Delete/5

        public ActionResult MemberHistory()
        {
            var lstmember = db.Memberships.Where(m => m.LastLoginDate != null).OrderByDescending(m => m.LastLoginDate).ToList();
            ViewBag.lstRole = db.UsersInRoles.Include(m=>m.Role).ToList();
            return PartialView(lstmember);
        }

        public ActionResult Delete(int id = 0)
        {
            var lstuserrole = db.UsersInRoles.ToList();
            ViewBag.lstuserrole = lstuserrole;
            Membership membership = db.Memberships.Find(id);
            ViewBag.userid = membership.UserId;
            if (membership == null)
            {
                return HttpNotFound();
            }
            return View(membership);
        }

        //
        // POST: /Admin/Membership/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Membership membership = db.Memberships.Find(id);
            var uir = db.UsersInRoles.Where(d => d.UserId == membership.UserId).ToList();
            foreach (var u in uir)
            {
                db.UsersInRoles.Remove(u);
                db.SaveChanges();
            }

            db.Memberships.Remove(membership);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Profile()
        {

            Membership member = db.Memberships.Where(m => m.Username == User.Identity.Name).FirstOrDefault();
            return View(member);
        }
        [HttpPost]
        public ActionResult Profile(Membership membership)
        {
            BlueDataWebEntities dbnew = new BlueDataWebEntities();
            Membership membertest = dbnew.Memberships.Where(m => m.Username == User.Identity.Name).FirstOrDefault();
            if (membership.Password != null || membership.Password == "")
            {
                membership.Password = md5(membership.Password);
            }
            if (membership.Password == null || membership.Password == "")
            {
                membership.Password = membertest.Password;
            }
            membership.LastLoginDate = membertest.LastLoginDate;
            if (ModelState.IsValid)
            {
                db.Entry(membership).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View();

        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

source/BlueDataWeb/Areas/Admin/Views/Membership/Create.cshtml
@model BlueDataWeb.Models.Entites.Membership
@using BlueDataWeb.Models.Entites;
@{
    ViewBag.Title = "Create";
    BlueDataWebEntities db = new BlueDataWebEntities();
    var role = db.Roles.ToList();
}
@using (Html.BeginForm("Create", "Membership", FormMethod.Post, new { id = "FormCreateUser" }))
{
    @Html.ValidationSummary(true)

    <div class="mar10 borall">
        <div class="floatl">
            <span class="floatl">
                <img src="/Areas/Admin/images/icon-48-generic.png" />
            </span>
            <span class="title-name">Thêm thành viên</span>
        </div>
        <ul class="floatr toolbar-list">
            <li id="toolbar-cancel" class="button">
                <a class="toolbar" href="/admin/Membership/Index">
                    <span class="icon-32-cancel"></span>
                    Hủy bỏ
                </a>
            </li>
            <li class="button">
                <div class="toolbar">
                    <span class="icon-32-apply"></span>
                    <input type="submit" value="Lưu" />
                </div>
            </li>
        </ul>
    </div>
    <!--end borall-->

    <div class="clear0"></div>
    <div class="mar10 borall">
        <div class="div100">

            <div>

                <fieldset class="fromlist">

                    <ul>
                        <li>
                            @Html.LabelFor(model => model.Username, "Tên đăng nhập")

                            <input class="inputbox" type="text" name="Username" id="UsernameCre" size="50" />
                            @Html.ValidationMessageFor(model => model.Username, null, new { @class = "validate" })

                            <span id="checkusername" class="clear" style="color: red; font-style: italic">@ViewBag.usernametest</span>
                        </li>
                        <li>
                            @Html.LabelFor(model => model.Password, "Mật khẩu")
                            <input class="inputbox" type="password" name="Password" id="PassCre" size="50" />
                            @Html.ValidationMessageFor(model => model.Password, null, new { @class = "validate" })
                            <span id="checkpassCre" class="clear" style="color: red; font-style: italic"></span>
                        </li>
                        <li>
                            @Html.LabelFor(model => model.Email, "Email")
                            <input class="inputbox" type="text" name="Email" id="EmailCre" size="50" />
                            @Html.ValidationMessageFor(model => model.Email, null, new { @class = "validate" })

                            <span id="checkemail" class="clear" style="color: red; font-style: italic">@ViewBag.emailtest</span>
                        </li>
                    </ul>
                </fieldset>
            </div>
        </div>
    </div>
    <div class="clear0"></div>
    <div class="mar10 borall">
        <div class="div100">

            <div>

                <fieldset class="fromlist">
                    <legend>Nhóm quyền</legend>
                    @foreach (var r in role)
                    {
                        <input type="checkbox" name="chk@(r.RoleId)" />
                        <span> @r.Description</span> <br />
                    }
                </fieldset>
            </div>
        </div>
    </div>
}

<div>
    <a class="toolbar back" href="#">Trở về danh sách</a>
</div>

<script type="text/javascript">
    function CheckNull() {

        var UsernameCre = $('#UsernameCre').val();
        var PassCre = $('#PassCre').val();
        var EmailCre = $('#EmailCre').val();

        if (UsernameCre == null || UsernameCre == "") {
            document.getElementById("checkusername").innerHTML = "vui lòng nhập Tên đăng nhập";
            return false;
        }
        if (PassCre == null || PassCre == "") {
            document.getElementById("checkpassCre").innerHTML = "vui lòng nhập mật khẩu";
            return false;
        }
        if (EmailCre == null || EmailCre == "") {
            document.getElementById("checkemail").innerHTML = "vui lòng nhập Email";
            return false;
        }

        return true;
    }
</script>

<script type="text/javascript">
    function CheckEmail() {
        if (!isValidEmailAddress($('#EmailCre').val())) {
            document.getElementById('checkemail').innerHTML = 'Email không hợp lệ';
            return false;
        }
        else {

            return true;

        }
    }

    function isValidEmailAddress(emailAddress) {
        var pattern = new RegExp(/^(("[\w-\s]+")|([\w-]+(?:\.[\w-]+)*)|("[\w-\s]+")([\w-]+(?:\.[\w-]+)*))(@@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$)|(@@\[?((25[0-5]\.|2[0-4][0-9]\.|1[0-9]{2}\.|[0-9]{1,2}\.))((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\.){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\]?$)/i);
        return pattern.test(emailAddress);
    }
</script>

<script type="text/javascript">
    $('#FormCreateUser').submit(function () {
        return !!(CheckNull() & CheckEmail());
    });
</script>

source/BlueDataWeb/Areas/Admin/Views/Membership/Delete.cshtml
@model BlueDataWeb.Models.Membership
@using BlueDataWeb.Models.Entites;
@{
    BlueDataWebEntities db = new BlueDataWebEntities();
    List<UsersInRole> lstrole = ViewBag.lstuserrole as List<UsersInRole>;
    ViewBag.Title = "Delete";
    int u=ViewBag.userid;
    
}

<div class="mar10 borall">
        <div class="floatl">
            <span class="floatl">
                <img src="/Areas/Admin/images/icon-48-generic.png" /></span>
            <span class="title-name">Xóa thành viên</span>
        </div>
        <ul class="floatr toolbar-list">
            <li id="toolbar-cancel" class="button">
                <a class="toolbar" href="/admin/Membership/Index">
                    <span class="icon-32-cancel"></span>
                    Hủy bỏ
                </a>
            </li>
           
        </ul>
    </div>
    <!--end borall-->

    <div class="clear0"></div>
    <div class="mar10 borall">
        <div class="div100">

            <div>

                <fieldset class="fromlist">
    <legend>Thông tin thành viên</legend>
                    <ul>
                     <li>
                        <label></label>

                        ID: <b>@Html.DisplayFor(model => model.UserId)</b>  <br />

                    </li>

                         <li>
                        <label></label>

                        Tên đăng nhập: <b>@Html.DisplayFor(model => model.Username)</b> <br />

                    </li>
    <li>
                        <label></label>

                        Email: <b>@Html.DisplayFor(model => model.Email)</b> <br />

                    </li>
                         <li>
                        <label></label>

                        Quyền: <b>@if (lstrole != null)
                        {
                            var lstroles = lstrole.Where(m => m.UserId == u).ToList();
                            if (lstroles.Count() > 0)
                            {
                                foreach (var role in lstroles)
                                {
                            <text>
                            @role.Role.Description .
                            </text>
                                }
                            }
                        }</b>  <br />

                    </li>

    </ul>
</fieldset>
                </div>
            </div>
        </div>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" class="button_sm" /> |
        @Html.ActionLink("Trở lại danh sách", "Index", null, new { @class="button_sm"})
    </p>
}

source/BlueDataWeb/Areas/Admin/Views/Membership/Details.cshtml
@model BlueDataWeb.Models.Membership
@using BlueDataWeb.Models.Entites;
@{
    BlueDataWebEntities db= new BlueDataWebEntities();
    List<UsersInRole> lstrole = ViewBag.lstuserrole as List<UsersInRole>;
    ViewBag.Title = "Details";
    int u=ViewBag.userid;
    
}
@{
    ViewBag.Title = "Details";
}

<div class="mar10 borall">
        <div class="floatl">
            <span class="floatl">
                <img src="/Areas/Admin/images/icon-48-generic.png" /></span>
            <span class="title-name">Thông tin thành viên</span>
        </div>
        <ul class="floatr toolbar-list">
            <li id="toolbar-cancel" class="button">
                <a class="toolbar" href="/admin/Home/Index">
                    <span class="icon-32-cancel"></span>
                    Quay lại
                </a>
            </li>
           
        </ul>
    </div>
    <!--end borall-->

 <div class="clear0"></div>
    <div class="mar10 borall">
        <div class="div100">

            <div>

                <fieldset class="fromlist">
    <legend>Thông tin thành viên</legend>

     <ul>
                     <li>
                        <label></label>

                        ID: <b>@Html.DisplayFor(model => model.UserId)</b>  <br />

                    </li>

                         <li>
                        <label></label>

                        Tên đăng nhập: <b>@Html.DisplayFor(model => model.Username)</b> <br />

                    </li>
    <li>
                        <label></label>

                        Email: <b>@Html.DisplayFor(model => model.Email)</b> <br />

                    </li>
                         <li>
                        <label></label>

                        Quyền: <b>@if (lstrole != null)
                        {
                            var lstroles = lstrole.Where(m => m.UserId == u).ToList();
                            if (lstroles.Count() > 0)
                            {
                                foreach (var role in lstroles)
                                {
                            <text>
                            @role.Role.RoleName .
                            </text>
                                }
                            }
                        }</b>  <br />

                    </li>

    </ul>

   
</fieldset>
                </div>
            </div>
        </div>

source/BlueDataWeb/Areas/Admin/Views/Membership/Edit.cshtml
@model BlueDataWeb.Models.Entites.Membership
@using BlueDataWeb.Models.Entites;
@{
    ViewBag.Title = "Create";
    BlueDataWebEntities db = new BlueDataWebEntities();
    var role = db.Roles.ToList();
    int userid = ViewBag.userid2;
    List<UsersInRole> lstrole = ViewBag.lstrole as List<UsersInRole>;
}

@{
    ViewBag.Title = "Edit";
}
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <div class="mar10 borall">
        <div class="floatl">
            <span class="floatl">
                <img src="/Areas/Admin/images/icon-48-generic.png" />
            </span>
            <span class="title-name">Cập nhật thành viên</span>
        </div>
        <ul class="floatr toolbar-list">
            <li id="toolbar-cancel" class="button">
                <a class="toolbar" href="/admin/Membership/Index">
                    <span class="icon-32-cancel"></span>
                    Hủy bỏ
                </a>
            </li>
            <li class="button">
                <div class="toolbar">
                    <span class="icon-32-apply"></span>
                    <input type="submit" value="Lưu" />
                </div>
            </li>
        </ul>
    </div>
    <!--end borall-->

    <div class="clear0"></div>
    <div class="mar10 borall">
        <div class="div100">

            <div>

                <fieldset class="fromlist">
                    <legend>Thông tin thành viên</legend>

                    <ul>
                        <li>

                            @Html.HiddenFor(model => model.UserId, new { size = "70" })
                            @Html.LabelFor(model => model.UserId, "ID: ")
                            <b>@Html.DisplayFor(model => model.UserId, new { size = "70" })</b>
                            @Html.ValidationMessageFor(model => model.UserId, null, new { @class = "validate" })
                        </li>
                        <li>
                            @Html.LabelFor(model => model.Username, "Tên đăng nhập: ")
                            @Html.HiddenFor(model => model.Username, new { size = "50" })
                            <b>@Html.DisplayFor(model => model.Username, new { size = "50" })</b>
                            @Html.ValidationMessageFor(model => model.Username, null, new { @class = "validate" })
                        </li>
                        <li>
                            @Html.LabelFor(model => model.Password, "Mật khẩu:")
                            @Html.PasswordFor(model => model.Password, new { size = "50" })
                            @* @Html.ValidationMessageFor(model => model.Email, null,new { @class="validate"})*@
                        </li>
                        <li>
                            @Html.LabelFor(model => model.Email, "Email:")
                            @Html.TextBoxFor(model => model.Email, new { size = "50" })
                            @* @Html.ValidationMessageFor(model => model.Email, null,new { @class="validate"})*@
                        </li>
                    </ul>

                    @* <p>
                            <input type="submit" value="Save" />
                        </p>*@
                </fieldset>
            </div>
        </div>
    </div>

    <div class="clear0"></div>
    <div class="mar10 borall">
        <div class="div100">

            <div>

                <fieldset class="fromlist">
                    <legend>Nhóm quyền</legend>
                    @foreach (var r in role)
                    {
                        UsersInRole userinrole = lstrole.Where(m => m.RoleId == r.RoleId).FirstOrDefault();
                        if (userinrole != null)
                        {
                            <input type="checkbox" name="check@(r.RoleId)" checked />
                        }

                        else
                        {
                            <input type="checkbox" name="check@(r.RoleId)" />
                        }
                        <span> @r.Description</span> <br />
                    }
                </fieldset>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại danh sách", "Index", null, new { @class = "button_sm" })
</div>

source/BlueDataWeb/Areas/Admin/Views/Membership/Index.cshtml
@model IEnumerable<BlueDataWeb.Models.Entites.Membership>
@using BlueDataWeb.Models.Entites;
@{
    ViewBag.Title = "Index";
    List<UsersInRole> lstrole = ViewBag.lstrole as List<UsersInRole>;
    
}
<div class="mar10 borall">
    <div class="floatl">
        <span class="floatl">
            <img src="/Areas/Admin/images/icon-48-generic.png" /></span>
        <span class="title-name">Thành viên</span>
    </div>
    <ul class="floatr toolbar-list">
        <li class="button">
            <a class="toolbar" href="/admin/Membership/Create">
                <span class="icon-32-new"></span>
                Thêm mới
            </a>
        </li>
    </ul>
</div>
<!--end borall-->

    <div class="clear0"></div>
    <div class="mar10 borall">
        <table  class="formtable">
            <tbody>
            <tr>
                <th>
                    UserID
                </th>
                <th>
                    UserName
                </th>
                <th>
                    Email
                </th>
                
                <th >
                    Quyền
                </th>
                
                <th style="width: 80px">Action</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserId)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Username)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @if (lstrole != null)
                        {
                            var lstroles = lstrole.Where(m => m.UserId == item.UserId).ToList();
                            if (lstroles.Count() > 0)
                            {
                                foreach (var role in lstroles)
                                {
                            <text>
                            @role.Role.Description<br />
                            </text>
                                }
                            }
                        }
                    </td>

                    <td>
                        <a class="button blue" title="Sửa" href="/admin/Membership/Edit?id=@item.UserId">
                            <div class="icon">
                                <p class="ic-edit"></p>
                            </div>
                        </a>
                        <a class="button red" href="/admin/Membership/Delete?id=@item.UserId" title="Xóa">
                            <div class="icon">
                                <p class="ic-delete"></p>
                            </div>
                        </a>
                    </td>
                </tr>
            }
</tbody>
        </table>
        <script>$("tr:even").css("background-color", "#f2f2f2");</script>
    </div>