source/BlueDataWeb/Areas/Admin/Controllers/HuongDanController.cs
using AutoMapper;
using BlueDataWeb.Helpers;
using BlueDataWeb.Models.CustomsModel;
using BlueDataWeb.Models.Entites;
using BlueDataWeb.Utility;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlueDataWeb.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin, AdminNews")]
    public class HuongDanController : BaseController
    {
        private BlueDataWebEntities db = new BlueDataWebEntities();

        //
        // GET: /Admin/News/

        public ActionResult Index()
        {
            var cate = db.NewCategories.Where(x => x.KeyName == "E_HuongDan" && x.AppID == this.AppID).FirstOrDefault();

            var data = new List<News>();

            if(cate != null)
            {
                data = db.News.Where(x => x.NewCategoriesID.Value == cate.NewCategoriesID
                    && (x.IsDelete == null || x.IsDelete.Value == false)).OrderBy(m => m.OrderBY).ToList();
            }
           
            return View(data);
        }

        public ActionResult Create()
        {
            var cate = db.NewCategories.Where(x => x.KeyName == "E_HuongDan").First();

            List<NewCategory> ListCateChild = new List<NewCategory>();

            ListCateChild.Add(cate);

            ViewBag.NewCategoriesID = new SelectList(ListCateChild, "NewCategoriesID", "Name");
            NewsModels newView = new NewsModels();
            newView.AppID = this.AppID;
            return View(newView);
        }

        //
        // POST: /Admin/News/Create

        [HttpPost, ValidateInput(false)]
        public ActionResult Create(News news)
        {
            if (ModelState.IsValid)
            {

                #region xử lý upload image

                if (Request.Files["img"] != null)
                {
                    string fullname = Request.Files["img"].FileName;
                    if (fullname != "")
                    {
                        news.ImagePath = UploadImageHelper.Upload(Request.Files["img"], Server.MapPath("~/Images/"), "News");
                    }
                }

                #endregion xử lý upload image

                news.CreatedDate = DateTime.Now;
                db.News.Add(news);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(news);
        }

        //
        // GET: /Admin/News/Edit/5

        public ActionResult Edit(int id = 0)
        {
            News news = db.News.Find(id);

            var cate = db.NewCategories.Where(x => x.KeyName == "E_HuongDan").First();
            List<NewCategory> ListCateChild = new List<NewCategory>();

            ListCateChild.Add(cate);

            ViewBag.NewCategoriesID = new SelectList(ListCateChild, "NewCategoriesID", "Name");

            NewsModels newView = Mapper.Map<News, NewsModels>(news);

            if (newView == null)
            {
                return HttpNotFound();
            }
            return View(newView);
        }

        //
        // POST: /Admin/News/Edit/5

        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(News news)
        {
            if (ModelState.IsValid)
            {


                #region xử lý upload image

                if (Request.Files["img"] != null)
                {
                    string fullname = Request.Files["img"].FileName;
                    if (fullname != "")
                    {
                        news.ImagePath = UploadImageHelper.Upload(Request.Files["img"], Server.MapPath("~/Images/"), "News");
                    }
                }

                #endregion xử lý upload image

                if (news.OrderBY == null)
                {
                    news.OrderBY = 0;
                }

                db.Entry(news).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(news);
        }

        //
        // GET: /Admin/News/Delete/5

        public ActionResult Delete(int id = 0)
        {
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        //
        // POST: /Admin/News/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            News news = db.News.Find(id);

            news.IsDelete = true;
            db.Entry(news).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

source/BlueDataWeb/Controllers/HuongDanController.cs
using BlueDataWeb.Models.Entites;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlueDataWeb.Controllers
{
    public class HuongDanController : BaseController
    {
        //
        // GET: /SanPham/
        private BlueDataWebEntities db = new BlueDataWebEntities();
        public ActionResult Index()
        {

            NewCategory newcategory = db.NewCategories.AsNoTracking().Where(m => m.KeyName == "E_HuongDan" && m.AppID == this.AppID).FirstOrDefault();
            var lstnew = new List<News>();
            if (newcategory!=null)
            {
                ViewBag.newcategory = newcategory;
                  lstnew = db.News.AsNoTracking().Where(m => m.NewCategoriesID == newcategory.NewCategoriesID && m.AppID == this.AppID
                    && (m.IsDelete == null || m.IsDelete.Value == false)).OrderBy(m => m.OrderBY).ToList();
            }

        
            return View("HuongDan_Index", lstnew);
        }

 

        public ActionResult Details(int id = 0)
        {
            News news = db.News.AsNoTracking().Where(x => x.AppID == this.AppID && x.NewsID == id).FirstOrDefault();
            NewCategory newcategory = db.NewCategories.AsNoTracking().Where(m => m.KeyName == "E_HuongDan" && m.AppID == this.AppID).FirstOrDefault();

            var lstAllSanPham = db.News.AsNoTracking().Where(x => x.NewCategoriesID == newcategory.NewCategoriesID && x.AppID == this.AppID &&
                (x.IsDelete == null || x.IsDelete.Value == false)).OrderBy(x => x.NewsID).ToList();
            ViewBag.lstAllSanPham = lstAllSanPham;
          
            return View(news);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

source/BlueDataWeb/Areas/Admin/Views/HuongDan/Create.cshtml
@model BlueDataWeb.Models.CustomsModel.NewsModels

@{
    ViewBag.Title = "Create";
}
<script src="~/nicEditor/nicEdit.js"></script>
<script>
    bkLib.onDomLoaded(function () {
        new nicEditor({ fullPanel: true, uploadURI: '/admin/Home/nicUpload' }).panelInstance('area');

    });
    bkLib.onDomLoaded(function () {
        new nicEditor({ fullPanel: true, uploadURI: '/admin/Home/nicUpload' }).panelInstance('area1');

    });
    bkLib.onDomLoaded(function () {
        new nicEditor({ fullPanel: true, uploadURI: '/admin/Home/nicUpload' }).panelInstance('area2');

    });
</script>
@using (Html.BeginForm("Create", "HuongDan", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <div class="mar10 borall">
        <div class="floatl">
            <span class="floatl">
                <img src="/Areas/Admin/images/icon-48-generic.png" />
            </span>
            <span class="title-name">Tạo HuongDan mới</span>
        </div>
        <ul class="floatr toolbar-list">
            <li id="toolbar-cancel" class="button">
                <a class="toolbar back" href="#">
                    <span class="icon-32-cancel"></span>
                    Hủy bỏ
                </a>
            </li>
            <li class="button">
                <div class="toolbar">
                    <span class="icon-32-apply"></span>
                    <input type="submit" value="Lưu" />
                </div>
            </li>
        </ul>
    </div>
    <!--end borall-->

    <div class="clear0"></div>
    <div class="mar10 borall">
        <div class="div100">
            <div>
                <fieldset class="fromlist">

                    @Html.HiddenFor(model => model.NewsID)
                    @Html.HiddenFor(model => model.AppID)
                    @Html.HiddenFor(model => model.CreatedDate)
                    @Html.HiddenFor(model => model.KeyName)


                    <ul>
                        <li>
                            @Html.LabelFor(model => model.Title, "Thể loại")
                            @Html.DropDownList("NewCategoriesID")
                        </li>
                        <li>
                            @Html.LabelFor(model => model.Title, "Tên  ")
                            @Html.TextBoxFor(model => model.Title, new { size = "66", @id = "tilte", @class = "TextRequire", @maxlength = "200" })
                            @Html.ValidationMessageFor(model => model.Title, null, new { @class = "validate" })
                        </li>



                        <li>
                            @Html.LabelFor(model => model.MetaTitle, "Meta Title")
                            @Html.TextBoxFor(model => model.MetaTitle, new { size = "80", @class = "TextRequire", @maxlength = "65" })
                            @Html.ValidationMessageFor(model => model.MetaTitle, null, new { @class = "validate" })
                        </li>

                        <li>
                            @Html.LabelFor(model => model.MetaKeywords, "Meta Keywords")
                            @Html.TextBoxFor(model => model.MetaKeywords, new { size = "80", @class = "TextRequire", maxlength = "100" })
                            @Html.ValidationMessageFor(model => model.MetaKeywords, null, new { @class = "validate" })
                        </li>
                        <li>
                            @Html.LabelFor(model => model.MetaDescription, "Meta Description")
                            @Html.TextAreaFor(model => model.MetaDescription, new { rows = 3, clos = 123, @class = "TextRequire", @maxlength = "160", style = "Width:595px;" })
                            @Html.ValidationMessageFor(model => model.MetaDescription, null, new { @class = "validate" })
                        </li>



                        <li>
                            @Html.LabelFor(model => model.IsNew, "Mới")
                            @Html.CheckBox("IsNew")
                        </li>


                        <li>
                            @Html.LabelFor(model => model.ShortDescription, "Mô tả ngắn")
                            @Html.TextAreaFor(model => model.ShortDescription, new { cols = "75", rows = "3", @id = "ShortDes", @class = "TextRequire", @maxlength = "400" })
                            @Html.ValidationMessageFor(model => model.ShortDescription, null, new { @class = "validate" })
                        </li>
                        <p id="ShortDesError" style="color: red"></p>

                        <li>
                            @Html.LabelFor(model => model.OrderBY, "Vị trí")
                            @Html.TextBoxFor(model => model.OrderBY, new { size = "66", @id = "tilte", @maxlength = "200", @type = "number", @min = "0", @class = "numericOnly" })

                        </li>


                        <li>
                            <label class="red">Hình ảnh  (Tỉ lệ  5 x 3) </label>
                            <input type="file" name="img" id="img" />
                            @Html.ValidationMessageFor(model => model.ImagePath, null, new { @class = "validate" })
                        </li>
                        <li>
                            <div>
                                @Html.LabelFor(model => model.Description, "Nội dung")
                                <div style="margin-left: 245px">
                                    @Html.TextAreaFor(model => model.Description, new { @id = "area", rows = 20, clos = 55, style = "Width:100%;", @class = "Descriptionvali" })
                                    @Html.ValidationMessageFor(model => model.Description, null, new { @class = "validate" })
                                </div>
                            </div>
                        </li>


                    </ul>
                </fieldset>
            </div>
        </div>
    </div>

    <div class="back_list">
        <a class="toolbar back" href="#">Trở về danh sách</a>
    </div>

}

source/BlueDataWeb/Areas/Admin/Views/HuongDan/Delete.cshtml
@model BlueDataWeb.Models.Entites.News

@{
    ViewBag.Title = "Delete HuongDan";
}

<div class="mar10 borall">
    <div class="floatl">
        <span class="floatl">
            <img src="/Areas/Admin/images/icon-48-generic.png" />
        </span>
        <span class="title-name">Xóa HuongDan</span>
    </div>
    <ul class="floatr toolbar-list">
        <li id="toolbar-cancel" class="button">
            <a class="toolbar" href="/admin/HuongDan/Index">
                <span class="icon-32-cancel"></span>
                Hủy bỏ
            </a>
        </li>
    </ul>
</div>
<!--end borall-->

<div class="clear0"></div>
<div class="mar10 borall">
    <div class="div100">

        <div>

            <fieldset class="fromlist">
                <legend>HuongDan</legend>

                <div class="display-label">
                    Tên  : <b>@Html.DisplayFor(model => model.Title)</b>  <br /> <br />
                </div>
                <div class="display-label">
                    Mô tả ngắn: <b>@Html.DisplayFor(model => model.ShortDescription)</b>  <br />
                </div>
            </fieldset>
        </div>
    </div>
</div>
@using (Html.BeginForm())
{
    <p>
        <input type="submit" value="Delete" class="button_sm" /> |
        @Html.ActionLink("Trở lại danh sách", "Index", null, new { @class = "button_sm" })
    </p>
}

source/BlueDataWeb/Areas/Admin/Views/HuongDan/Edit.cshtml
@model BlueDataWeb.Models.CustomsModel.NewsModels

@{
    ViewBag.Title = "Edit HuongDan";
}
<script src="~/nicEditor/nicEdit.js"></script>
<script>
    bkLib.onDomLoaded(function () {
        new nicEditor({ fullPanel: true, uploadURI: '/admin/Home/nicUpload' }).panelInstance('area');

    });
    bkLib.onDomLoaded(function () {
        new nicEditor({ fullPanel: true, uploadURI: '/admin/Home/nicUpload' }).panelInstance('area1');

    });
    bkLib.onDomLoaded(function () {
        new nicEditor({ fullPanel: true, uploadURI: '/admin/Home/nicUpload' }).panelInstance('area2');

    });
</script>
@using (Html.BeginForm("Edit", "HuongDan", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <div class="mar10 borall">
        <div class="floatl">
            <span class="floatl">
                <img src="/Areas/Admin/images/icon-48-generic.png" />
            </span>
            <span class="title-name">Cập nhật HuongDan</span>
        </div>
        <ul class="floatr toolbar-list">
            <li id="toolbar-cancel" class="button">
                <a class="toolbar" href="/admin/Outsourcing/Index">
                    <span class="icon-32-cancel"></span>
                    Hủy bỏ
                </a>
            </li>
            <li class="button">
                <div class="toolbar">
                    <span class="icon-32-apply"></span>
                    <input type="submit" value="Lưu" />
                </div>
            </li>
        </ul>
    </div>
    <!--end borall-->

    <div class="clear0"></div>
    <div class="mar10 borall">
        <div class="div100">
            <div>
                <fieldset class="fromlist">

                    @Html.HiddenFor(model => model.NewsID)
                    @Html.HiddenFor(model => model.AppID)
                    @Html.HiddenFor(model => model.CreatedDate)
                    @Html.HiddenFor(model => model.KeyName)


                    <ul>
                        <li>
                            @Html.LabelFor(model => model.Title, "Thể loại")
                            @Html.DropDownList("NewCategoriesID")
                        </li>
                        <li>
                            @Html.LabelFor(model => model.Title, "Tên  ")
                            @Html.TextBoxFor(model => model.Title, new { size = "66", @id = "tilte", @class = "TextRequire", @maxlength = "200" })
                            @Html.ValidationMessageFor(model => model.Title, null, new { @class = "validate" })
                        </li>



                        <li>
                            @Html.LabelFor(model => model.MetaTitle, "Meta Title")
                            @Html.TextBoxFor(model => model.MetaTitle, new { size = "80", @class = "TextRequire", @maxlength = "65" })
                            @Html.ValidationMessageFor(model => model.MetaTitle, null, new { @class = "validate" })
                        </li>

                        <li>
                            @Html.LabelFor(model => model.MetaKeywords, "Meta Keywords")
                            @Html.TextBoxFor(model => model.MetaKeywords, new { size = "80", @class = "TextRequire", maxlength = "100" })
                            @Html.ValidationMessageFor(model => model.MetaKeywords, null, new { @class = "validate" })
                        </li>
                        <li>
                            @Html.LabelFor(model => model.MetaDescription, "Meta Description")
                            @Html.TextAreaFor(model => model.MetaDescription, new { rows = 3, clos = 123, @class = "TextRequire", @maxlength = "160", style = "Width:595px;" })
                            @Html.ValidationMessageFor(model => model.MetaDescription, null, new { @class = "validate" })
                        </li>



                        <li>
                            @Html.LabelFor(model => model.IsNew, "Mới")
                            @Html.CheckBox("IsNew")
                        </li>


                        <li>
                            @Html.LabelFor(model => model.ShortDescription, "Mô tả ngắn")
                            @Html.TextAreaFor(model => model.ShortDescription, new { cols = "75", rows = "3", @id = "ShortDes", @class = "TextRequire", @maxlength = "400" })
                            @Html.ValidationMessageFor(model => model.ShortDescription, null, new { @class = "validate" })
                        </li>
                        <p id="ShortDesError" style="color: red"></p>

                        <li>
                            @Html.LabelFor(model => model.OrderBY, "Vị trí")
                            @Html.TextBoxFor(model => model.OrderBY, new { size = "66", @id = "tilte", @maxlength = "200", @type = "number", @min = "0", @class = "numericOnly" })

                        </li>


                        <li>
                            <label class="red">Hình ảnh  (Tỉ lệ  5 x 3) </label>
                            <input type="file" name="img" id="img" />
                            @Html.HiddenFor(m => m.ImagePath)

                            <img src="/Images/News/@(Model.ImagePath)" width="85px" height="50px" />
                        </li>
                        <li>
                            <div>
                                @Html.LabelFor(model => model.Description, "Nội dung")
                                <div style="margin-left: 245px">
                                    @Html.TextAreaFor(model => model.Description, new { @id = "area", rows = 20, clos = 55, style = "Width:100%;", @class = "Descriptionvali" })
                                    @Html.ValidationMessageFor(model => model.Description, null, new { @class = "validate" })
                                </div>
                            </div>
                        </li>


                    </ul>
                </fieldset>
            </div>
        </div>
    </div>
}

<div>
    <a class="toolbar back" href="#">Trở về danh sách</a>
</div>

source/BlueDataWeb/Areas/Admin/Views/HuongDan/Index.cshtml
@model IEnumerable<BlueDataWeb.Models.Entites.News>

@{
    ViewBag.Title = "HuongDan";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="mar10 borall">
    <div class="floatl">
        <span class="floatl">
            <img src="/Areas/Admin/images/icon-48-generic.png" />
        </span>
        <span class="title-name">HuongDan</span>
    </div>
    <ul class="floatr toolbar-list">
        <li class="button">
            <a class="toolbar" href="/admin/HuongDan/Create">
                <span class="icon-32-new"></span>
                Thêm mới
            </a>
        </li>
    </ul>
    <table id="example" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>
                    STT
                </th>
                <th>
                    Tên
                </th>

                <th>
                    View
                </th>

                <th>
                    Vị trí
                </th>

                <th>
                    Hình
                </th>

               
                <th>
                    Ngày tạo
                </th>

                <th width="150px"></th>
            </tr>
        </thead>

      

        <tbody>
            @{
                int num = 0;
            }
            @foreach (var item in Model)
            {
                num++;
                <tr>
                    <td style="width:5%">
                        @num
                    </td>
                    <td style="width:40%">

                        <a class="button " title="Sửa" href="/admin/DichVu/Edit/@item.NewsID">

                            @Html.DisplayFor(modelItem => item.Title)
                        </a>

                      
                    </td>
                    <td>
                        <a target="_blank" title="@item.Title" href="@Url.RouteUrl("HuongDandetail", new { title = BlueDataWeb.Utility.HelperSEO.ToSeoUrl(item.Title), id = item.NewsID })" class="">
                           View
                        </a>
                    </td>
                    <td>
                        @item.OrderBY
                    </td>
                    <td>
                        <img src="/Images/News/@(item.ImagePath)" width="70px" height="40px" />
                    </td>

                    <td>@string.Format("{0:dd/MM/yyyy}", item.CreatedDate)</td>
                    <td class="text-right">
                        <div>
                            <a class="button " href="/admin/Outsourcing/Delete/@item.NewsID" title="Xóa">

                                <img class="icon_mane" src="~/Areas/Admin/Content/images/icon_delete.png" />
                            </a>

                            <a class="button " title="Sửa" href="/admin/Outsourcing/Edit/@item.NewsID">

                                <img class="icon_mane" src="~/Areas/Admin/Content/images/icon_edit.png" />
                            </a>
                            
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<!--end borall-->
@section Scripts {
    <script>
        $(document).ready(function () {
            $('#example').DataTable();
        });
    </script>
}